// ================================================================
// File: smrita-backend/src/seeds/seedProducts.js
// Run: node src/seeds/seedProducts.js
// ================================================================

require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const products = [
  {
    name: "Chandan",
    nameHindi: "चंदन",
    subtitle: "Sacred Sandalwood",
    description: "Crafted from premium & natural ingredients, our Chandan incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription: "Made of Cow-Dung, Chandan (Sandalwood Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "https://res.cloudinary.com/dgs7leir0/image/upload/v1776282980/c_urjpa7.jpg",
    category: "Sandalwood",
    scent: "Woody, Warm, Sacred",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["bestseller", "meditation"],
    rating: 4.9,
    numReviews: 128,
    inStock: true,
    featured: true,
    isActive: true,
    color: "#8B6914",
    ingredients: "Cow-Dung, Chandan (Sandalwood Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    name: "Gulab",
    nameHindi: "गुलाब",
    subtitle: "Rose of the Divine",
    description: "Crafted from premium & natural ingredients, our Gulab (Rose) incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription: "Made of Cow-Dung, Rose (waste rose petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "https://res.cloudinary.com/dgs7leir0/image/upload/v1776282980/r_cj8nqq.jpg",
    category: "Floral",
    scent: "Sweet, Floral, Romantic",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["popular", "floral"],
    rating: 4.8,
    numReviews: 95,
    inStock: true,
    featured: true,
    isActive: true,
    color: "#9B2335",
    ingredients: "Cow-Dung, Rose (waste rose petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    name: "Lavender",
    nameHindi: "लैवेंडर",
    subtitle: "Lavender Bliss",
    description: "Crafted from premium & natural ingredients, our Lavender incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription: "Made of Cow-Dung, flower waste (lavender flower petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "https://res.cloudinary.com/dgs7leir0/image/upload/v1776282982/l_wnb0ek.jpg",
    category: "Floral",
    scent: "Floral, Fresh, Calming",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["classic", "calming"],
    rating: 5.0,
    numReviews: 212,
    inStock: true,
    featured: true,
    isActive: true,
    color: "#4A235A",
    ingredients: "Cow-Dung, flower waste (lavender flower petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    name: "Mogra",
    nameHindi: "मोगरा",
    subtitle: "Arabian Jasmine",
    description: "Crafted from premium & natural ingredients, our Mogra (Jasmine) incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription: "Made of Cow-Dung, Arabian Jasmine (Mogra petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "https://res.cloudinary.com/dgs7leir0/image/upload/v1776282980/m_bofd5o.jpg",
    category: "Floral",
    scent: "Jasmine, Sweet, Intoxicating",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["floral", "goddess"],
    rating: 4.9,
    numReviews: 67,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#2D6A2F",
    ingredients: "Cow-Dung, Arabian Jasmine (Mogra petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    name: "Tulsi Dhoop",
    nameHindi: "तुलसी धूप",
    subtitle: "Holy Basil Purifier",
    description: "Grown in sacred soil, Tulsi is the most revered plant in Hinduism. These sticks purify the air and the soul simultaneously.",
    longDescription: "Tulsi (Holy Basil) is considered the most sacred plant in Hindu tradition, associated with Vishnu and used in every major ritual. Our Tulsi Dhoop uses leaves harvested from plants grown in temple gardens in Vrindavan.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1536147116438-62679a5e01f2?w=600&q=80",
    category: "Herbal",
    scent: "Fresh, Green, Purifying",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["herbal", "purifying"],
    rating: 4.7,
    numReviews: 88,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#2D6A4F",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    name: "Loban Resin",
    nameHindi: "लोबान",
    subtitle: "Ancient Frankincense",
    description: "Pure Loban resin sticks — the same incense that has been burned in temples and churches across the ancient world for millennia.",
    longDescription: "Loban (Benzoin/Frankincense resin) is one of humanity's oldest sacred substances, traded along the ancient Silk Road and burned in every major religious tradition on Earth.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80",
    category: "Resin",
    scent: "Deep, Balsamic, Ancient",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["ancient", "meditation"],
    rating: 4.8,
    numReviews: 74,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#6B4423",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    name: "Mogra Bela",
    nameHindi: "मोगरा बेला",
    subtitle: "Jasmine Moonlight",
    description: "The intoxicating scent of Mogra jasmine flowers, harvested under moonlight when their fragrance blooms most intensely.",
    longDescription: "Mogra (Arabian Jasmine) is the queen of night-blooming flowers. This delicate, intensely floral incense is traditionally offered to goddesses and is said to attract love, abundance, and spiritual blessings.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    category: "Floral",
    scent: "Jasmine, Sweet, Intoxicating",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["floral", "goddess"],
    rating: 4.8,
    numReviews: 103,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#F0EAD6",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    name: "Havan Samagri",
    nameHindi: "हवन सामग्री",
    subtitle: "Sacred Fire Blend",
    description: "A sacred blend of 21 herbs and resins traditionally used in Vedic fire ceremonies. Adapted into incense sticks for daily rituals.",
    longDescription: "Our Havan Samagri stick is based on an ancient recipe that includes camphor, guggul, agar wood, clove, cardamom, and 16 other sacred herbs and resins.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600&q=80",
    category: "Vedic",
    scent: "Camphor, Herbal, Sacred",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["vedic", "ceremony"],
    rating: 4.9,
    numReviews: 156,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#D4860A",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    name: "Oud Majlis",
    nameHindi: "ऊद मजलिस",
    subtitle: "Arabian Oud Wood",
    description: "The rarest wood in the world — Oud (Agarwood) — from the forests of Assam. One of the most prized fragrances in human history.",
    longDescription: "Oud (Agarwood) is the resinous heartwood of the Aquilaria tree, formed only when the tree responds to fungal infection — a process that takes decades. Our Oud Majlis uses genuine Assamese agarwood chips.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    category: "Luxury",
    scent: "Smoky, Complex, Deep",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    stockCount: 50,
    sticksPerPack: 50,
    tags: ["luxury", "oud", "rare"],
    rating: 5.0,
    numReviews: 45,
    inStock: true,
    featured: false,
    isActive: true,
    color: "#2C1810",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    // Purane products delete karo
    await Product.deleteMany({});
    console.log('🗑️  Old products deleted');

    // Naye products insert karo
    await Product.insertMany(products);
    console.log('✅ 9 products seeded successfully!');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
};

seedDB();
